version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hotel-booking-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_booking
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: hotel-booking-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hotel_booking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: hotel
      SPRING_DATASOURCE_PASSWORD: hotel123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    stdin_open: true
    tty: true

volumes:
  mysql_data:
